function sanitizePackageName(name) {
  return String(name || "weather-mcp")
    .toLowerCase()
    .replace(/[^a-z0-9-]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .slice(0, 48) || "weather-mcp";
}

export function createWeatherMcpBundle(name = "weather-mcp") {
  const packageName = sanitizePackageName(name);

  const packageJson = {
    name: packageName,
    version: "1.0.0",
    type: "module",
    scripts: {
      start: "node server.js"
    },
    dependencies: {
      axios: "^1.8.4",
      fastmcp: "^2.10.2"
    }
  };

  return {
    "package.json": `${JSON.stringify(packageJson, null, 2)}\n`,
    "server.js": `import axios from "axios";
import { FastMCP } from "fastmcp";

const server = new FastMCP({
  name: "${packageName}",
  version: "1.0.0"
});

server.tool({
  name: "get_weather",
  description: "Get current weather for latitude and longitude",
  parameters: {
    type: "object",
    properties: {
      latitude: { type: "number" },
      longitude: { type: "number" }
    },
    required: ["latitude", "longitude"]
  },
  execute: async ({ latitude, longitude }) => {
    const response = await axios.get("https://api.open-meteo.com/v1/forecast", {
      params: {
        latitude,
        longitude,
        current: "temperature_2m,wind_speed_10m"
      }
    });

    const current = response.data.current || {};
    return {
      content: [
        {
          type: "text",
          text: \`Temperature: \${current.temperature_2m}°C, Wind: \${current.wind_speed_10m} km/h\`
        }
      ]
    };
  }
});

await server.start({
  transportType: "httpStream",
  httpStream: {
    port: Number(process.env.PORT || 8080),
    endpoint: "/mcp"
  }
});
`,
    "Dockerfile": `FROM node:20-slim

WORKDIR /app
COPY package.json ./
RUN npm install
COPY . .

ENV PORT=8080
CMD ["npm", "start"]
`,
    "README.md": `# ${packageName}

Simple remote MCP server generated by the Jumeau extension.
`
  };
}
